<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\pay_with_payula\Controller\PayulaController;
use Symfony\Component\HttpFoundation\Request;

/**
 * Implements hook_help().
 */
function pay_with_payula_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.pay_with_payula':

      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The <strong>Pay with PayU Latam module</strong> is used to create a payment gateway that
        allows you to configure your Drupal Commerce store for the use of the
        <em>PayU Latam</em> payment provider.') . '</p>';
      $output .= '<h3>' . t('Important') . '</h3>';
      $output .= '<dl>';
      $output .= '<p>' . t('When configuring the new payment gateway you must make sure to create it
        with the name of <strong>PayU LA</strong> so that the machine name is <em>payu_la</em>. <strong>This is mandatory</strong>.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_cron().
 */

function pay_with_payula_cron () {

  $orders = \Drupal::entityTypeManager()
    ->getStorage('commerce_order')
    ->loadByProperties([
      'state' => 'draft',
      'locked' => 1,
    ]);

  $payula = new PayulaController; 
  $client = \Drupal::httpClient();

  /**Recorre las ordenes pendientes */
  $idOrders = array_keys($orders);
  foreach ($idOrders as $idOrder){

    $res = $client->post(
      'https://api.payulatam.com/reports-api/4.0/service.cgi',
      [
        'json' => [
          'test'=>false,
          'language'=>'es',
          'command'=> 'ORDER_DETAIL_BY_REFERENCE_CODE',
          'merchant' =>[
            'apiLogin'=>'wICKsDReLHjKA55',
            'apiKey'=>'Gx4i62k95k4tKUd0xriNGWquad',
          ],
          'details'=>[
            'referenceCode'=> $idOrder
          ],
        ],
      ],
    );

    $body =  simplexml_load_string($res->getBody());
    $json = json_encode($body);
    $arr = json_decode($json, true);
    
    /**Pregunta si se pago la orden */
    if($res->getStatusCode() == 200 
      && !$arr['result'] 
      && $arr['result']['payload']['order']['status'] == 'CAPTURED') {
      
      /**Para actualizar si el pago es correcto */
      $path = '/confirmPayuLA?payment_method=2&value=159000&currency=COP&reference_pol=555&reference_code_pol=APPROVED&reference_sale=229&sign=df3a4244f089b4ddba3a3dc5cc411934&state_pol=4&merchant_id=508029';
      $request = Request::create(
        $path,
        'POST',
      );
      $payula->onNotify($request);
    }
  } // end for
  $alex=1;

}