commerce_payment.commerce_payment_gateway.plugin.redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    merchantId:
      type: string
      label: 'Merchant Id'
    api_key:
      type: string
      label: 'API key'
    accountId:
      type: string
      label: 'Account Id'
    apiLogin:
      type: string
      label: 'API Login'
    urlProvider:
      type: string
      label: 'Url Provider'
    urlReport:
      type: string
      label: 'Url Report'
